version: '3.7'

services:
  server:
    image: tm-server:latest
    restart: always
    ports:
      - "2350:2350/tcp"
      - "2350:2350/udp"
      - "3450:3450/tcp"
      - "3450:3450/udp"
      - "5005:5005/tcp"
      - "5005:5005/udp"
    environment:
      SERVER_IP: "0.0.0.0"
      SERVER_PORT: "2350"
      SERVER_TITLE: "Trackmania"
      SERVER_NAME: "harha/trackmania-server-docker"
    volumes:
      - ./cfg_server.xml:/home/server/tm_server/UserData/Config/cfg_server.xml
      - ./cfg_tracklist.xml:/home/server/tm_server/UserData/Maps/MatchSettings/cfg_tracklist.xml
      - ./maps:/home/server/tm_server/UserData/Maps/Campaigns
